Algoritmo "03"
//3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.

Var
nome:caractere
salario:real
Inicio
 escreva ("Qual o seu nome?")
 leia(nome)
 escreva ("Qual o seu salário?")
 leia(salario)
 escreva("Olá ",nome,",Seu salário é de ",salario,"R$.")

Fimalgoritmo