Algoritmo "10"
//10) Faça um algoritmo que leia a largura e altura de uma parede, calcule e
//mostre a área a ser pintada e a quantidade de tinta necessária para o serviço,
//sabendo que cada litro de tinta pinta uma área de 2metros quadrados.

Var
nome:caractere
salario,s,s1:inteiro
n1,n2,n3,n4,n5,n6,n7:real
Inicio
 escreva ("Valor da altura:")
 leia(n1)
 escreva ("Valor da largura:")
 leia(n2)
 n3<-(n1*n2)/2
 escreva (n3," Litros de tinta necessária.")
Fimalgoritmo