Algoritmo "er13"

Var
a1,a2:real
n1,n2,n3,n4,n5:inteiro
nome,nome1:caractere
Inicio
n2<-0
n3<-10
escreval("-------------------")
escreval("1 até 10:(1)")
escreval("10 até 1:(2)")
escreval("sair(3)")
leia(n1)
escreval("------------------")
escolha n1
caso 1
repita
escreval (n2)
n2<-n2+1
ate (n2>10)
caso 2
repita
escreval (n3)
n3<-n3-1
ate (n3<0)
caso 3
escreval ("teminando o programa!")
fimescolha


Fimalgoritmo