Algoritmo "69"
//69) [DESAFIO] Desenvolva um programa que leia o primeiro termo e a razão de uma
//PA (Progressão Aritmética), mostrando na tela os 10 primeiros elementos da PA e
//a soma entre todos os valores da sequência.

Var
n1,n2,n3,n4,n5,p1:inteiro
a1,a2,a3,a4:real
Inicio
para  n1<- 0 ate 100 passo 10  faça
n3<-n3+n1
se (n1>90) então
escreva(n1,"=")
senão
escreva(n1,"+")
fimse
fimpara
escreva (n3)
Fimalgoritmo