Algoritmo "95"
//95) Refaça o exercício 90, só que agora em forma de função Somador(), que vai
//receber dois parâmetros e vai retornar o resultado da soma entre eles para o
//programa principal.
Var
n1,n2,n3:inteiro
funcao soma(a,b:inteiro):inteiro
 var
 a1,a2:inteiro
 inicio
 a1<-a+b
 retorne a1


 fimfuncao
Inicio
escreva("Valor 1:")
leia(n1)
escreva("Valor 2:")
leia(n2)
n3<-soma(n1,n2)
escreva(n3)
Fimalgoritmo