Algoritmo "99"
//99) Faça um programa que possua uma função chamada Potencia(), que vai receber
//dois parâmetros numéricos (base e expoente) e vai calcular o resultado da
//exponenciação.
//Ex: Potencia(5,2) vai calcular 52 = 25

Var
n1,n2,n3:inteiro
n4:real
funcao soma(a,b:inteiro):real
 var
 a3,a4:inteiro
 a1,a2:real
 inicio

 a1<-a^b


 retorne a1


 fimfuncao
Inicio
escreva("Base:")
leia(n1)
escreva("Expoente:")
leia(n2)
n4<-soma(n1,n2)
escreva("O resultado é ",n4)
Fimalgoritmo