Algoritmo "44"
//44) Crie um algoritmo que leia o valor inicial da contagem, o valor final e o
//incremento, mostrando em seguida todos os valores no intervalo:
//Ex: Digite o primeiro Valor: 3
//Digite o último Valor: 10
//Digite o incremento: 2
//Contagem: 3 5 7 9 Acabou!

Var
n1,n2,n3:inteiro
Inicio
escreva ("Inicio:")
leia(n1)
escreva ("Fim:")
leia(n2)
escreva ("Salto:")
leia(n3)
enquanto (n1<=n2) faça
 escreval(n1)
 n1<-n1+n3
 fimenquanto


Fimalgoritmo