Algoritmo "Exercicio-42"
//42) Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!
Var
contagem,valor:inteiro
Inicio
contagem<-0
escreva ("até quanto quer contar?")
leia(valor)
enquanto (contagem<=valor) faça
escreval (contagem)
contagem<-contagem+1
fimenquanto




Fimalgoritmo