Algoritmo "86"
//86) Crie um programa que tenha um procedimento Gerador() que, quando chamado,
//mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
//Ex: Ao chamar Gerador() aparece:
//+-------=======------+
// Olá, Mundo!
//+-------=======------+
Var
 procedimento ola()
 inicio
 escreval ("--------------")
 escreval("Olá,mundo!")
 escreval("---------------")
 fimprocedimento
Inicio
ola()
Fimalgoritmo