Algoritmo "87"
//87) Crie um programa que melhore o procedimento Gerador() da questão anterior
//para que mostre uma mensagem personalizada, passada como parâmetro.
//Ex: Ao chamar Gerador("Aprendendo Portugol") aparece:
//+-------=======------+
// Aprendendo Portugol
Var
 procedimento ola()
 inicio
 escreval ("--------------")
 escreval("Olá,mundo!")
 escreval("Aprenda portugol.")
 escreval("---------------")
 fimprocedimento
Inicio
ola()
Fimalgoritmo