Algoritmo "18"
//18) Faça um programa que leia o ano de nascimento de uma pessoa, calcule a idade
//dela e depois mostre se ela pode ou não votar.18) Faça um programa que leia o ano de nascimento de uma pessoa, calcule a idade
//dela e depois mostre se ela pode ou não votar.

Var
 a1,b1,c1:inteiro
 d1:real
Inicio
 escreva("Qual o ano do seu nascimento?")
 leia(a1)
 b1<-2021-a1
 se (b1>=18) então
 escreva ("Pode votar.")
 senão
 escreva("Não pode votar.")
 fimse

Fimalgoritmo

