Algoritmo "56"
//56) Crie um programa que leia vários números pelo teclado e mostre no final o
//somatório entre eles.
//Obs: O programa será interrompido quando o número 1111 for digitado


Var
n1,n2,n3,n4,n5,n6,n7,n8:inteiro
a1,a2,a3:real
Inicio
n1<-0
enquanto (n1<1111) faça
escreva("Valor1?")
leia(n2)
escreva("Valor2?")
leia(n3)
n4<-n2+n3
escreval(n4)
escreva("Quer continuar?")
leia(n1)
fimenquanto



fimalgoritmo